// @vitest-environment jsdom
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { ClasesAlumnoData } from "@/types/clases-alumno.types";
const m=vi.hoisted(()=>({fetch:vi.fn()}));vi.mock("@/lib/fetch-autenticado",()=>({fetchAutenticado:m.fetch}));
import { HistorialClases } from "./historial-clases";
const data:ClasesAlumnoData={alumno:{id:"a",nombre_completo:"Pérez, Ana"},resumen:{total:12,por_resultado:{PROXIMA:2,ASISTIO:3,AUSENTE:1,SIN_REGISTRAR_COMO_DICTADA:1,CANCELADA_CENTRO:1,CANCELADA_ALUMNO:1,RESERVA_VENCIDA:1,BAJA_ALUMNO:1,QUITADA_CENTRO:1},asistio_sin_control:1,clases_con_control:3,porcentaje_asistencia:67},items:[{inscripcion_id:"i",turno_id:"t",fecha:"2026-10-09",hora_inicio:"10:00",hora_fin:"11:00",materia:{id:"m",nombre:"Matemática"},profesor:"Laura Méndez",aula:"Aula 1",resultado:"ASISTIO",sin_control_asistencia:true}],paginacion:{total:12,pagina_actual:1,total_paginas:2,por_pagina:10}};
let host:HTMLDivElement;let root:Root;
async function flush(){await act(async()=>{await new Promise(r=>setTimeout(r,0));});}
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});vi.clearAllMocks();m.fetch.mockResolvedValue({ok:true,json:async()=>({data})});host=document.createElement("div");document.body.appendChild(host);root=createRoot(host);});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();});
async function render(){await act(async()=>root.render(<HistorialClases alumnoId="a"/>));await flush();}
async function input(label:string,value:string){const el=host.querySelector<HTMLInputElement|HTMLSelectElement>(`[aria-label="${label}"]`)!;await act(async()=>{const proto=el instanceof HTMLInputElement?HTMLInputElement.prototype:HTMLSelectElement.prototype;Object.getOwnPropertyDescriptor(proto,"value")!.set!.call(el,value);el.dispatchEvent(new Event(el instanceof HTMLInputElement?"input":"change",{bubbles:true}));if(el instanceof HTMLInputElement)el.dispatchEvent(new Event("change",{bubbles:true}));});await flush();}
describe("E02 tabla, filtros y estados UI",()=>{
 it("nueve resultados y porcentaje con denominador; link real sin montos",async()=>{await render();expect(host.textContent).toContain("67%");expect(host.textContent).toContain("2 de 3 clases dictadas con control");expect(host.textContent).toContain("Asistió (sin control de asistencia)");expect(host.querySelector('a[href="/turnos/t"]')).not.toBeNull();expect(host.querySelectorAll("select option")).toHaveLength(10);expect(host.querySelectorAll("thead th")).toHaveLength(6);expect(host.textContent).not.toContain("Precio");});
 it("página 2 y resultado reinicia 1",async()=>{await render();await act(async()=>host.querySelector<HTMLButtonElement>('[aria-label="Página siguiente"]')!.click());await flush();expect(m.fetch.mock.calls.at(-1)?.[0]).toContain("pagina=2");await input("Resultado","ASISTIO");expect(m.fetch.mock.calls.at(-1)?.[0]).toContain("pagina=1");expect(m.fetch.mock.calls.at(-1)?.[0]).toContain("resultado=ASISTIO");});
 it("fechas combinadas, rango inválido local y limpiar",async()=>{await render();await input("Desde","2026-10-09");await input("Hasta","2026-10-10");expect(m.fetch.mock.calls.at(-1)?.[0]).toContain("desde=2026-10-09");expect(m.fetch.mock.calls.at(-1)?.[0]).toContain("hasta=2026-10-10");await input("Hasta","2026-10-08");expect(host.querySelector('[role="alert"]')?.textContent).toContain("posterior");await act(async()=>Array.from(host.querySelectorAll("button")).find(b=>b.textContent==="Limpiar filtros")!.click());await flush();expect(m.fetch.mock.calls.at(-1)?.[0]).not.toContain("desde=");});
 it("sin coincidencias, limpiar y vacío literal",async()=>{await render();m.fetch.mockResolvedValue({ok:true,json:async()=>({data:{...data,items:[],paginacion:{...data.paginacion,total:0,total_paginas:0}}})});await input("Resultado","BAJA_ALUMNO");expect(host.textContent).toContain("No se encontraron clases para los filtros elegidos");await act(async()=>Array.from(host.querySelectorAll("button")).find(b=>b.textContent==="Limpiar filtros")!.click());await flush();expect(host.textContent).toContain("Este alumno todavía no tiene clases registradas");});
 it("error y reintento",async()=>{m.fetch.mockResolvedValueOnce({ok:false,json:async()=>({error:{message:"Error de carga"}})});await render();expect(host.querySelector('[role="alert"]')?.textContent).toContain("Error de carga");await act(async()=>host.querySelector("button")!.click());await flush();expect(host.querySelector("table")).not.toBeNull();});
 it("descarta respuesta tardía",async()=>{await render();let resolver:(r:unknown)=>void=()=>{};m.fetch.mockImplementationOnce(()=>new Promise(r=>{resolver=r;}));await input("Resultado","AUSENTE");expect(host.textContent).toContain("Cargando clases");await input("Resultado","ASISTIO");await act(async()=>resolver({ok:true,json:async()=>({data:{...data,items:[]}})}));await flush();expect(host.querySelector("table")).not.toBeNull();});
});
